notify-update: true
enable: true
max-durability: 3
crops:
  CARROTS:
    enable: true
    max-age: 7
    damage: 1
    drops:
      item: CARROT
      amount:
        min: 2
        max: 5
    experience:
      enable: true
      chance: 30
      amount: 1
    particle:
      enable: true
      type: TOTEM
      offsetX: 0.3
      offsetY: 0.3
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.75
      pitch: 1.0
  POTATOES:
    enable: true
    max-age: 7
    damage: 1
    drops:
      item: POTATO
      amount:
        min: 2
        max: 5
    experience:
      enable: true
      chance: 30
      amount: 1
    particle:
      enable: true
      type: TOTEM
      offsetX: 0.3
      offsetY: 0.3
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.75
      pitch: 1.0
  WHEAT:
    enable: true
    max-age: 7
    damage: 1
    drops:
      item: WHEAT
      amount:
        min: 1
        max: 1
    experience:
      enable: true
      chance: 30
      amount: 1
    particle:
      enable: true
      type: TOTEM
      offsetX: 0.3
      offsetY: 0.3
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.75
      pitch: 1.0
  BEETROOTS:
    enable: true
    max-age: 7
    damage: 1
    drops:
      item: BEETROOT
      amount:
        min: 1
        max: 1
    experience:
      enable: true
      chance: 30
      amount: 1
    particle:
      enable: true
      type: TOTEM
      offsetX: 0.3
      offsetY: 0.3
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.75
      pitch: 1.0
  COCOA:
    enable: true
    max-age: 7
    damage: 1
    drops:
      item: COCOA_BEAN
      amount:
        min: 2
        max: 3
    experience:
      enable: true
      chance: 30
      amount: 1
    particle:
      enable: true
      type: TOTEM
      offsetX: 0.3
      offsetY: 0.3
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.75
      pitch: 1.0
  NETHER_WART:
    enable: true
    max-age: 7
    damage: 1
    drops:
      item: NETHER_WART
      amount:
        min: 2
        max: 4
    experience:
      enable: true
      chance: 30
      amount: 1
    particle:
      enable: true
      type: TOTEM
      offsetX: 0.3
      offsetY: 0.3
      offsetZ: 0.3
      count: 25
    sound:
      enable: true
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.75
      pitch: 1.0
